// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYCBvqnTZnhO63eGSQAC823qXPBfX4s0Y',
    appId: '1:513900388753:web:0777af0ea69c06ce98fa30',
    messagingSenderId: '513900388753',
    projectId: 'geonho-eb81b',
    authDomain: 'geonho-eb81b.firebaseapp.com',
    storageBucket: 'geonho-eb81b.firebasestorage.app',
    measurementId: 'G-H785RRY938',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwFCh_dnBvWRCdrGp-G0lbVD5b-V5YPwc',
    appId: '1:513900388753:android:3030c514e9aa17e798fa30',
    messagingSenderId: '513900388753',
    projectId: 'geonho-eb81b',
    storageBucket: 'geonho-eb81b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMmodzE5JdSGntHQfp55kbyLf3_p66hy8',
    appId: '1:513900388753:ios:117a8573ce2ff76a98fa30',
    messagingSenderId: '513900388753',
    projectId: 'geonho-eb81b',
    storageBucket: 'geonho-eb81b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMmodzE5JdSGntHQfp55kbyLf3_p66hy8',
    appId: '1:513900388753:ios:117a8573ce2ff76a98fa30',
    messagingSenderId: '513900388753',
    projectId: 'geonho-eb81b',
    storageBucket: 'geonho-eb81b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYCBvqnTZnhO63eGSQAC823qXPBfX4s0Y',
    appId: '1:513900388753:web:ef0ab2eda0f4298898fa30',
    messagingSenderId: '513900388753',
    projectId: 'geonho-eb81b',
    authDomain: 'geonho-eb81b.firebaseapp.com',
    storageBucket: 'geonho-eb81b.firebasestorage.app',
    measurementId: 'G-2RVVRWFY75',
  );
}
